# fly.toml file generated for pydc on 2023-03-15T21:42:36+08:00

app = "pydc"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "nrt"
processes = []

[env]

[experimental]
  auto_rollback = true
